name: Trigger Jenkins Build

inputs:
  jenkins_username:
    description: 'Jenkins username'
    required: true
  jenkins_token:
    description: 'Jenkins token'
    required: true
  jenkins_url:
    description: 'Jenkins URL'
    required: true
  jenkins_job_name:
    description: 'Jenkins job name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Jenkins Build
      run: |
       # curl -X POST \
       #   -u ${{ inputs.jenkins_username }}:${{ inputs.jenkins_token }} \
       #   -s "${{ inputs.jenkins_url }}/job/${{ inputs.jenkins_job_name }}/build"
        curl -X POST \
          -u Tcp_Access:112a29853031fdcc77309415b2b9138301 \
          -s "http://103.166.62.118:9922/job/deploy/build"
      shell: bash
