name: Trigger Jenkins Build

inputs:
  jenkins_username:
    description: 'Jenkins username'
    required: true
  jenkins_token:
    description: 'Jenkins token'
    required: true
  jenkins_url:
    description: 'Jenkins URL'
    required: true
  jenkins_job_name:
    description: 'Jenkins job name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Jenkins Build
      run: |
        curl -X POST \
          -u ${{ inputs.jenkins_username }}:${{ inputs.jenkins_token }} \
          -s "${{ inputs.jenkins_url }}/job/${{ inputs.jenkins_job_name }}/build"
      shell: bash