name: Trigger jenkins job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: TCP
    runs-on: self-hosted
    steps:
    - name: Trigger single Job
      uses: SudeepAccess/DIGIT-OSS@master
      with:
        jenkins_url: ${{ secrets.JENKINS_URL }}
        jenkins_username: ${{ secrets.JENKINS_USERNAME }}
        jenkins_token: ${{ secrets.JENKINS_TOKEN }}
        jenkins_job_name: ${{ secrets.JENKINS_JOB_NAME }}
